project:
  type: website
  output-dir: docs
  resources:
  - "/.nojekyll"
  - "/CNAME"

website:
  title: "OffshoreWindHabitat.info"
  navbar:
    left:
      - href: /7319ea8f88497a65f3888850e7592e21ce668d9b/index.qmd
        text: Home
      - href: /7319ea8f88497a65f3888850e7592e21ce668d9b/about.qmd
        text: About

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
